### ISSUE TITLE
[Request] Support for QVD files

### ISSUE THREAD

**Issue by sillasgonzaga** [Stan125/GREA#12]
There's a BI department at my work that stores data as QVD files. I would love to load them using R.

**Comment by Stan125** [comment]
Hi there, 
a quick google search didn't get me any results on how to read them - are you sure there is also a known solution to read those files?

**Comment by sillasgonzaga** [comment]
Well, that's the problem. QVD is a proprietary format and cannot still be read by R.

I opened this issue to see if anyone could come up with a solution for working with QVD files, but there seems to be none.

**Comment by Stan125** [comment]
These files come from qlikview, right? I think the fastest way of proceeding would be to just export the files from qlikview in a different format that can be read.
For the longer term: Try submitting an issue to [haven](https://github.com/hadley/haven) or [readr](https://github.com/hadley/readr)!
On this end, the issue cannot be solved; I can only implement it as the reading is already done with another function.

All the Best,
Stani
