### ISSUE TITLE
about the seperators

### ISSUE THREAD

**Issue by xiaoliSTR** [Stan125/GREA#17]
Hi Stan125, 

thanks a lot for building up this addin. 
I'm wondering if you'd like to add one optional function to the seperator which enables one choosing the separator that is not included in your list? I think it would be very helpful for many users.

Best, 
meged

**Comment by Stan125** [comment]
Hi meged,

there will be a "Advanced options" tab to specify additional separators.

All the Best,
Stani

**Comment by Stan125** [comment]
Advanced Options are now part of `GREA` as of a566c93a0d791d1c07985b350b41678f8d638c01.
