### ISSUE TITLE
It doesn´t parse

### ISSUE THREAD

**Issue by mvsfrazao** [Stan125/GREA#18]
Dear sirs,

I´m trying to import a single spreadsheet (attached) and it doesn´t parse at all.
The print screen is also attached.
Thanks for any help in advance!

![grea_test](https://cloud.githubusercontent.com/assets/20372682/16936025/1eeaffdc-4d3a-11e6-83b4-917eb3ddc193.png)
[sims_data.xlsx](https://github.com/Stan125/GREA/files/370499/sims_data.xlsx)

**Comment by Stan125** [comment]
For me, it works. Just specify to import the second sheet in the first tab and you should be good to go!
![bildschirmfoto 2016-07-19 um 10 48 22](https://cloud.githubusercontent.com/assets/17404160/16943899/6d84d2bc-4d9e-11e6-9fe4-eaec6bf7d28e.png)

**Comment by mvsfrazao** [comment]
I´ve found the problem:
When I`m manually called the rio package, the GREA didn´t install the following packages (dependencies):
xtable
httpuv
urltools
heaven
feather
readODS
readxl

After installing them, it worked smoothly.
Hint: the GREA installation script could check all if all the necessary packages is in the library user

Great work!! Thank you!

**Comment by Stan125** [comment]
Great! There seems to have been something wrong in the installation - it should have installed all those packages.
