### ISSUE TITLE
Unable to install GREA

### ISSUE THREAD

**Issue by aalokjha** [Stan125/GREA#20]
Hi Stan - 

I followed the instructions to install this addin but got the following error. Can you please help resolve this?

> devtools::install_github("Stan125/GREA")
> Downloading GitHub repo Stan125/GREA@master
> Error in packageVersion("curl") : package ‘curl’ not found

Can you please help resolve this?

Thanks!

**Comment by Stan125** [comment]
try installing curl first:
`install.packages("curl")`
and if that works you should be able to continue with:
`devtools::install_github("Stan125/GREA")`

**Comment by aalokjha** [comment]
Thanks for the help. I installed 'curl' but another issue cropped up. Below is the error message. 

package ‘curl’ successfully unpacked and MD5 sums checked

The downloaded binary packages are in
    C:\Users\alokranjan\AppData\Local\Temp\RtmpSuKbV0\downloaded_packages

> devtools::install_github("Stan125/GREA")
> Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
>   there is no package called ‘digest’
> devtools::install_github("Stan125/GREA")
> Error in loadNamespace(j <- i[[1L]], c(lib.loc, .libPaths()), versionCheck = vI[[j]]) : 
>   there is no package called ‘digest

**Comment by Stan125** [comment]
something seems to be weird with the location of your packages. 
First, look where your packages were installed to. Then, check where R looks for your packages. You can do this with `.libPaths()`. Take a look [here](http://stackoverflow.com/a/19407300).
If this still doesn't help, it seems like you have to install every package that's missing with `install.packages("package_name")`.

**Comment by aalokjha** [comment]
Thanks for all help!

**Comment by aalokjha** [comment]
Thanks much Stan! I was able to install it finally. Thanks for all your help!!

**Comment by vstarkweather** [comment]
Hi Stan:

Here's the error message I get on attempting the download and installation of GREA:

```
> devtools::install_github("Stan125/GREA")
Downloading GitHub repo Stan125/GREA@master
from URL https://api.github.com/repos/Stan125/GREA/zipball/master
Error in curl::curl_fetch_memory(url, handle = handle) : 
  Peer certificate cannot be authenticated with given CA certificates
```

**Comment by aalokjha** [comment]
I would suggest to close all the open R instances on your computer first. Then start afresh with the code above. It should work. Else, check for the library path, if it is correctly getting downloaded there. That should resolve it. At least that is what worked for me.

**Comment by Stan125** [comment]
It looks more like a problem with the download using `curl`. Maybe check if you have the newest version of curl. Also, check if you have the right system time. Look at [this](http://stackoverflow.com/questions/14566864/peer-certificate-cannot-be-authenticated-with-known-ca-certificates-using-php-oa).
