### ISSUE TITLE
Dataset Name validation

### ISSUE THREAD

**Issue by DavidMartinOnGitHub** [Stan125/GREA#22]
The filename that I imported was named something like **salmon-x.csv**. The auto-suggested name would then be **salmon-x** which is not a legal R variable name and gets interpreted as a calculation with R complaining that **object 'salmon' not found**.

The workaround is simple enough, I just overwrote the suggested name.

It might be preferable to replace the '-' character by underscores in the suggested name. Of course there might be other characters such as '+' that are legal in filenames but might not be R-friendly.

**Comment by Stan125** [comment]
Aha! Interesting bug. Thank you for reporting it. I will fix this in an upcoming release :)
