### ISSUE TITLE
Generate code

### ISSUE THREAD

**Issue by Bisaloo** [Stan125/GREA#4]
I think it would be good if your package generated the appropriate code to open the file in a non-interactive mode.

This way, the user doesn't have to go through a interactive process every single time they want to re-run the code. Interactive is good for user experience, especially for novices, but it is more time consuming.

**Comment by Stan125** [comment]
Hi Bisaloo,

thanks for your input. Implementing this was my idea originally, but `shiny::fileInput()` gives only the path of a copied, temporary file (which is deleted after closing the app) and not the original file that was chosen by the user. I think this could still be done via some functions of the package `shinyFiles` or just using the plain `file.choose()` function. I will implement it, when I get around to it.

**Comment by Stan125** [comment]
Commit 3286c7c78de9135d8c7e335f0c361a640bdfe34e now pastes the code into the console! Try it out!

**Comment by Bisaloo** [comment]
Great! Good job!

I am wondering whether it would be better to paste it in the source code or in the console. I have no strong opinion on this.

**Comment by Stan125** [comment]
I'm always annoyed when the code is pasted to some location inside my document, so I figured the console would be best :)
