### ISSUE TITLE
Depend on rio?

### ISSUE THREAD

**Issue by leeper** [Stan125/GREA#6]
Please take this suggestion with a grain of salt since I am the (co-)author of the package, but why not use [rio](https://cran.r-project.org/web/packages/rio/index.html) to handle the file importing? This way you don't need to reimplement all of the complex handling of file types, etc. No pressure, of course.

**Comment by Stan125** [comment]
Hi leeper,

Thanks for your suggestion, I didn't know this existed. Good idea!

**Comment by Stan125** [comment]
Implemented with a25d5aca2e28d380f5d84731a4ae029828385fe2
